CREATE TABLE Sheet1(Welcome_to_the_IT_College VARCHAR(10));
INSERT INTO Sheet1 (Welcome_to_the_IT_College) VALUES 
('Select your desired course to view modules'),
('Computer Science'),
('View Modules '),
('Software Engineering'),
('View Modules '),
('Cyber Security'),
('View Modules '),
('Computer Science Modules'),
('COS1903'),
('Scala Programming'),
('View Details '),
('COS1920'),
('Database Management'),
('View Details '),
('Module Details – COS1903'),
(''),
('Scala Programming'),
('Description:'),
('This module introduces the core principles of functional programming using Scala. Students will explore high-order functions, immutability, pattern matching, and concurrency.'),
('Contents:'),
('- Introduction to Scala'),
('- Functional vs. Object-Oriented Programming'),
('- Recursion and Higher-Order Functions'),
('- Concurrency with Futures and Actors '),
('← Back to Modules '),
('Module Details – COS1920'),
(''),
('Database Management'),
('Description:'),
('Explore database theory and practice. Learn about relational databases, SQL, ER diagrams, and data normalization.'),
('Contents:'),
('- SQL Queries and Joins'),
('- Relational Data Modeling'),
('- Entity-Relationship Diagrams'),
('- Database Normalization'),
('← Back to Modules '),
('Software Engineering Modules'),
('SE3906'),
('Interaction Design'),
('View Details '),
('Module Details – SE3906'),
(''),
('Interaction Design'),
('Description:'),
('Learn user-centred design techniques for creating effective user interfaces and experiences.'),
('Contents:'),
('- UX Principles'),
('- Wireframing'),
('- Usability Testing'),
('- Accessibility Standards'),
('← Back to Modules '),
('Cyber Security Modules'),
('SE3901'),
('C Programming'),
('View Details '),
('SE3902'),
('Computer Law and Cyber Security Management'),
('View Details '),
('SE3903'),
('Linux Security'),
('View Details '),
('SE3904'),
('Cyber Threat Intelligence and Incident Response'),
('View Details '),
('Module Details – SE3903'),
(''),
('Linux Security'),
('Description:'),
('Learn how to defend and secure Linux operating systems against modern cyber threats.'),
('Contents:'),
('- SELinux and AppArmor'),
('- User & File Permissions'),
('- iptables and FirewallD'),
('- Intrusion Detection Tools'),
('← Back to Modules '),
('COS1911'),
('Object Oriented Programming'),
('View Details '),
('COS1920'),
('Database Management'),
('View Details '),
('Module Details – COS1911'),
(''),
('Object Oriented Programming'),
('Description:'),
('Learn the principles of object-oriented programming using Java. This module covers class structure, encapsulation, inheritance, polymorphism, and abstraction.'),
('Contents:'),
('- Java class design'),
('- OOP principles (encapsulation, inheritance, polymorphism)'),
('- Abstract classes and interfaces'),
('- Practical coding exercises'),
('← Back to Modules '),
('Module Details – COS1920'),
(''),
('Database Management'),
('Description:'),
('Understand the core concepts of relational databases. Learn how to write complex SQL queries, create database schemas, and design ER diagrams.'),
('Contents:'),
('- SQL: SELECT, INSERT, JOIN, GROUP BY'),
('- Entity-Relationship diagrams'),
('- Normalisation and schema design'),
('- Real-world relational database modeling'),
('← Back to Modules '),
('SE3410'),
('Web Application Penetration Testing'),
('View Details'),
('SE3406'),
('Fuzzy Logic & Knowledge Based Systems'),
('View Details'),
('SE3613'),
('Data Mining'),
('View Details'),
('Module Details – SE3410'),
(''),
('Web Application Penetration Testing'),
('Description:'),
('Gain hands-on skills in identifying and exploiting web vulnerabilities. Topics include the OWASP Top 10, XSS, SQL Injection, CSRF, and ethical hacking practices. '),
('Contents:'),
('- OWASP Top 10 security flaws'),
('- Web application reconnaissance'),
('- Exploiting XSS and SQL injection'),
('- Defensive coding and mitigation '),
('← Back to Modules '),
('Module Details – SE3406'),
(''),
('Fuzzy Logic & Knowledge Based Systems'),
('Description:'),
('Explore fuzzy logic and its application in AI decision-making systems. Learn to build intelligent systems that make decisions under uncertainty. '),
('Contents:'),
('- Fuzzy sets and membership functions'),
('- Rule-based reasoning'),
('- Knowledge representation'),
('- Building expert systems '),
('← Back to Modules '),
('Module Details – SE3613'),
(''),
('Data Mining'),
('Description:'),
('Learn techniques for extracting knowledge from large datasets. This module covers classification, clustering, regression, and association rule learning. '),
('Contents:'),
('- Supervised and unsupervised learning'),
('- Decision trees and clustering'),
('- Association rule mining'),
('- Introduction to data mining tools '),
('← Back to Modules '),
('Module Details – SE3901'),
(''),
('C Programming'),
('Description:'),
('Learn low-level system programming using the C language. Explore variables, control structures, memory management, and file handling. '),
('Contents:'),
('- Pointers and memory'),
('- Functions and arrays'),
('- File I/O'),
('- Structs and header files '),
('← Back to Modules '),
('Module Details – SE3902'),
(''),
('Computer Law & Cyber Security Management'),
('Description:'),
('Understand the legal frameworks and policies in cybersecurity. Explore cybercrime law, GDPR, risk assessments, and developing organisational policies. '),
('Contents:'),
('- GDPR and data privacy'),
('- Cybercrime legislation'),
('- Risk and compliance management'),
('- Policy writing and frameworks '),
('← Back to Modules '),
('Module Details – SE3904'),
(''),
('Cyber Threat Intelligence & Incident Response'),
('Description:'),
('Gain the skills to detect and respond to cyber threats. Learn threat modeling, digital forensics, and design effective incident response plans. '),
('Contents:'),
('- Threat intelligence lifecycle'),
('- Indicators of compromise'),
('- Incident response frameworks'),
('- Forensic tools and techniques '),
('← Back to Modules '),
('Register for a Course'),
(''),
('Student Registration Form'),
('Registration Complete'),
(''),
('Thank you for registering!'),
('← Return to Homepage '),
('Register as a Student');